#!/usr/bin/env fish

# /conf -- location for the list of configured domains
# /certs -- location where keys are stored
# $ACCOUNT_EMAIL -- email to associate with these registrations

if not test -f /conf
    echo "/conf is not a valid file. No config!" >&2
    exit 1
end

if not test -d /certs
    echo "/certs is not a valid directory" >&2
    exit 1
end

if not string length $ACCOUNT_EMAIL >/dev/null
    echo "ACCOUNT_EMAIL must be set" >&2
    exit 1
end

set -l doms (cat /conf | jq -r 'join(",")')

set -l extra_args

if test -n "$DRY_RUN"; and test "$DRY_RUN" = 'true'
    set extra_args --dry-run $extra_args
end

exec certbot certonly $extra_args \
    --email $ACCOUNT_EMAIL --non-interactive --agree-tos \
    --expand \
    --config-dir /certs \
    --standalone -d "$doms"
